name: razorpay_dart
description: "A Dart package for interacting with the Razorpay API."
version: 0.0.3
repository: https://github.com/devalfaz/razorpay_dart
homepage: https://github.com/devalfaz/razorpay_dart
issues: https://github.com/devalfaz/razorpay_dart/issues

topics:
  - razorpay
  - payment
  - gateway
  - finance

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.6
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  http: ^1.3.0
  package_config: ^2.2.0
  pointycastle: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  mockito: ^5.4.6
  test: ^1.25.15
  very_good_analysis: ^7.0.0

